name: Publish Artifact

on:
  push:
    branches: [develop]

jobs:

  publish:
    name: Release 'feature-module-2' Library
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Gradle and wrapper
        uses: action/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant Permission for Gradlew to Execute
        run: chmod +x gradlew

      - name: Build AAR
        run: bash ./gradlew :feature-module-2:assemble

      - name: Publish to GitHub Packages
        run: bash ./gradlew :feature-module-2:publish
        env:
          GITHUB_USER: $${{ github.actor }}
          GITHUB_TOKEN: $${{ secrets.GITHUB_TOKEN }}

